# Our directory is 'amd64', so Maven can find us (via os.arch)
# But our arch as known to the NativeLoader will be x86_64
# (which is what the 'arch' command shows)

ARCH = x86_64

NATIVEHOME = $(abspath ../../)

-include Makefile.env

include ../Makefile

# eof

